= AlethZero Chocolatey package for Windows
chevdor
0.8.2-POC8

== Summary 
Chocolatey package for the Ethereum C++ client: AlethZero. This allows (un)installing the client on windows as you would with homebrew or apt-get. 

You can visit the project page: https://github.com/chevdor/ethereum-chocolatey

The Github project for AlethZero is located at https://github.com/ethereum/cpp-ethereum

You can find the list of available packages here: https://chocolatey.org/packages?q=alethzero&prerelease=true&sortOrder=relevance

== (Un)Installation
First ensure you have installed chocolatey: https://chocolatey.org/. You will find a one-liner on the site to install it.

NOTE: At the moment, AlethZero is still a beta, so is the chocolatey package, so dont´t forget the -pre flag!

To find the latest package: 

 clist -pre alethzero

To install AlethZero:

 cinst -pre alethzero

To install the latest version if you already have a version installed:

 cinst -pre -force alethzero

To uninstall AlethZero:

 cuninst alethzero

== What is the package doing on my machine?
=== Install

* Download the latest build from the official repo to your temp folder
* Unzip it 

=== Uninstall

== Can I trust it?
No! Never trust. Check it yourself!

You can find the scripts here: 

* Install: https://github.com/chevdor/ethereum-chocolatey/blob/master/tools/chocolateyInstall.ps1
* Uninstall: https://github.com/chevdor/ethereum-chocolatey/blob/master/tools/chocolateyUninstall.ps1

You can also see the script on the chocolatey.org website.

Finally, you may download the package and open it locally using https://chocolatey.org/packages/nugetpackageexplorer and look at the scripts before executing anything.

