= Ethereum Chocolatey package for Windows
chevdor, 0.8.2-POC8

image::https://badges.gitter.im/Join%20Chat.svg[link="https://gitter.im/chevdor/ethereum-chocolatey?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]

image::https://badge.waffle.io/chevdor/ethereum-chocolatey.svg?label=ready&title=ready[link="http://waffle.io/chevdor/ethereum-chocolatey"] 
image::https://badge.waffle.io/chevdor/ethereum-chocolatey.svg?label=in%20progress&title=in%20progress[link="http://waffle.io/chevdor/ethereum-chocolatey"] 
image::https://badge.waffle.io/chevdor/ethereum-chocolatey.svg?label=bug&title=bug[link="http://waffle.io/chevdor/ethereum-chocolatey"] 

== Summary 
Chocolatey package for the Ethereum software: AlethZero, Mix, Mist,... 
This allows (un)installing the client on windows as you would with homebrew or apt-get. 

You can visit the project page on https://github.com/chevdor/ethereum-chocolatey[GitHub].

The Github project for AlethZero is located at https://github.com/ethereum/cpp-ethereum[here].

You can find the list of available packages on https://chocolatey.org/packages?q=ethereum&prerelease=true&sortOrder=relevance[chocolatey.org] or read more about https://github.com/chocolatey/choco/wiki[chocolatey].

WARNING: The *latest* version changes very often. The package downloads the latest. It means that unlike the chocolatey package may suggest, you are not installing *THE* version x.y.z but the current candidate for this version. The official versions will not be flagged with -pre

== (Un)Installation
First ensure you have installed chocolatey: https://chocolatey.org/. You will find a one-liner on the site to install it.

NOTE: At the moment, AlethZero is still a beta, so is the chocolatey package, so dont´t forget the -pre flag!

To find the latest package: 

 clist -pre alethzero-stable

To install AlethZero:

 cinst -pre alethzero-stable

To install the latest version if you already have a version installed:

 cinst -pre -force alethzero-stable

To uninstall AlethZero:

 cuninst alethzero-stable

== What is the package doing on my machine?
=== Install

* Download the latest build from the official repo 
* Store the file into your temp folder
* Unzip it in your %ProgramFiles%\AlethZero
* Delete the temp file

=== Uninstall

* Wipe the install folder %ProgramFiles%\AlethZero
* Delete the registry keys related to AlethZero

NOTE: AlethZero is a subkey of Ethereum in the registry. The uninstall process does *not* remove the ethereum key.

== Can I trust it?
No! Never trust. Check it yourself!

You can find the scripts here: 

* Install: https://github.com/chevdor/ethereum-chocolatey/blob/master/tools/chocolateyInstall.ps1[chocolateyInstall.ps1]
* Uninstall: https://github.com/chevdor/ethereum-chocolatey/blob/master/tools/chocolateyUninstall.ps1[chocolateyUninstall.ps1]

You can also see the script on the chocolatey.org website.

Finally, you may download the package and open it locally using https://chocolatey.org/packages/nugetpackageexplorer[NuGET Package Explorer] and look at the scripts before executing anything.

== Known issues

* If you install the package from powershell, the installer will throw you in the install folder at the end of the install. If you run from a regular shell, it will not do that and leave you where you are.

* The uninstall does not remove the ethereum registry entry. This is wanted as more software may come under this key in the future and that would be a bad idea to be so aggressive.

* Make sure to open your command prompt as Admin unless UAC is disabled. Otherwise you won´t be able to create a new folder in "Program Files" and the install will fail.

== How to contribute or build the package yourself?

You are very welcome to clone this repository and submit pull requests.
You can also easily build the package yourself using the "chocolatey pack" command:

 cpack

The local install then goes with:
 
 cinst -pre alethzero-stable -source %cd%
